(test
 (name test_spiffe_id)
 (modules test_spiffe_id)
 (libraries tinysvid))

(test
 (name test_bundle_svid)
 (modules test_bundle_svid)
 (libraries tinysvid))

(test
 (name test_correspondence)
 (modules test_correspondence)
 (libraries tinysvid svid_model))

(test
 (name test_der)
 (modules test_der)
 (libraries tinysvid))

(test
 (name test_x509)
 (modules test_x509)
 (libraries tinysvid))

(test
 (name test_chain)
 (modules test_chain)
 (libraries tinysvid))

(test
 (name test_zx)
 (modules test_zx)
 (libraries tinysvid tinysvid_zx svid_model))

(test
 (name test_uds)
 (modules test_uds)
 (libraries tinysvid_io unix))

(test
 (name test_h2)
 (modules test_h2)
 (libraries tinysvid))

(test
 (name test_pb)
 (modules test_pb)
 (libraries tinysvid))
