#!/usr/bin/env bash
# M29: regenerate FOOTPRINT.md from measured sizes. Every local number
# is measured from the tree at generation time. The spire-agent
# reference size is the one external constant, pinned below with its
# provenance and the command that re-measures it.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"

# Reference point: the official spire-agent release binary.
# Measured 2026-08-27 from spire-1.15.3-linux-arm64-musl.tar.gz
# (github.com/spiffe/spire releases): extract, then
# `wc -c spire-1.15.3/bin/spire-agent`.
spire_version="1.15.3"
spire_agent_bytes=62267216

dune build --root "$here" demo/fetch_svid.exe
exe="$here/_build/default/demo/fetch_svid.exe"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cp "$exe" "$tmp/fetch_svid"
chmod +w "$tmp/fetch_svid"
strip "$tmp/fetch_svid"

sz() { wc -c < "$1" | tr -d ' '; }
comma() { LC_ALL=en_US.UTF-8 printf "%'d" "$1"; }
ratio() { awk -v a="$1" -v b="$2" 'BEGIN { printf "%.2f", a / b }'; }
pct() { awk -v a="$1" -v b="$2" 'BEGIN { printf "%.2f%%", 100 * a / b }'; }

exe_bytes=$(sz "$exe")
stripped_bytes=$(sz "$tmp/fetch_svid")

zx_total=0
rust_total=0
rows=""
for name in zx_core zx_step zx_window zx_charset; do
  zso="$here/zx/out/$name.so"
  rso="$here/zx/rust/out/$name.so"
  if [ ! -f "$zso" ]; then
    echo "footprint: $zso missing (run ./gates.sh --zx)"
    exit 1
  fi
  zb=$(sz "$zso")
  zx_total=$((zx_total + zb))
  if [ -f "$rso" ]; then
    rb=$(sz "$rso")
    rust_total=$((rust_total + rb))
    rows="$rows| $name | $(comma "$zb") | $(comma "$rb") | $(ratio "$rb" "$zb") |
"
  else
    rows="$rows| $name | $(comma "$zb") | - | - |
"
  fi
done
if [ "$rust_total" -gt 0 ]; then
  total_row="| total | $(comma "$zx_total") | $(comma "$rust_total") | $(ratio "$rust_total" "$zx_total") |"
else
  total_row="| total | $(comma "$zx_total") | - | - |"
fi

cat > "$here/FOOTPRINT.md" <<REPORT
# Footprint report (M29)

Generated by \`./footprint.sh\` on $(date +%F). Every local number is
measured at generation time; the spire-agent reference is pinned in
the script with its provenance.

## Verified artifacts (SBF .so)

The four ZxCaml artifacts carry the model-certified checks (the A4/A5
gap invariant, the SPIFFE charsets, the Coupled bundle step, the
window-plus-gap check). The Rust column is the dependency-free no_std
equivalent from M19, built for the same SBF machine; method and
honesty notes (black_box pins against whole-check constant folding)
are in \`zx/SIZES.md\`. The M30 gate holds the zx sizes to
\`zx/size-budget.txt\`.

| artifact | zxcaml (B) | rust (B) | rust/zxcaml |
|----------|-----------:|---------:|------------:|
$rows$total_row

## Host client static footprint

\`demo/fetch_svid.exe\` is the complete Workload API client from M28:
UDS transport, HTTP/2 framing, HPACK, protobuf, DER, X.509, and the
typed SPIFFE parsers, as one native executable with the OCaml runtime
linked in. Stripping removes symbol and debug load only.

| binary | bytes |
|--------|------:|
| fetch_svid.exe as built | $(comma "$exe_bytes") |
| fetch_svid.exe stripped | $(comma "$stripped_bytes") |

## Comparison

spire-agent is the reference implementation's full agent (node
attestation, plugin machinery, caching, server channel), so this is a
scope comparison, not a like-for-like one. The point is the order of
magnitude a typed, stdlib-only client needs.

| binary | bytes | share of spire-agent |
|--------|------:|---------------------:|
| spire-agent $spire_version (linux-arm64-musl) | $(comma "$spire_agent_bytes") | 100% |
| tinysvid fetch_svid (stripped, macos-arm64) | $(comma "$stripped_bytes") | $(pct "$stripped_bytes" "$spire_agent_bytes") |
| all four zx artifacts together | $(comma "$zx_total") | $(pct "$zx_total" "$spire_agent_bytes") |
REPORT

echo "footprint: wrote FOOTPRINT.md"
